# Generated by Django 4.2.7 on 2023-11-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0002_stock_ticker"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
